require_relative "../config/environment.rb"

seed_array1 = ["EAGLE", "GAME", "WASHER", "BERRY", "SOLDIER", "SPRING", "PIANO", "COURT", "SPOT", "ENGINE", "SHAKESPEARE", "PAPER", "SOUND", "IVORY", "AMERICA", "JUPITER", "SHARK", "EUROPE", "SOUL"]
seed_array2 = ["SQUARE", "GREECE", "CIRCLE", "BED", "PLASTIC", "DWARF", "AIR", "CALF", "CLIFF", "LAB", "RULER", "BOMB", "GAS", "CAST", "MOSCOW", "CHANGE", "PALM", "TRIP", "CRANE"]
seed_array3 = ["ROSE", "FOREST", "BOTTLE", "WALL", "PANTS", "WIND", "GRACE", "KID", "OLIVE", "TABLE", "TIE", "SPINE", "PRESS", "WEB", "FAN", "FIGHTER", "WAKE", "WHALE", "DIAMOND"]
seed_array4 = ["MEXICO", "EYE", "POST", "RAY", "LITTER", "HEAD", "COMIC", "MAMMOTH", "MINT", "BUG", "HEART", "HOOD", "HORSESHOE", "HONEY", "NOVEL", "PIPE", "GLOVE", "BRIDGE", "ROBIN"]
seed_array5 = ["STREAM", "DICE", "SHIP", "HORN", "CARD", "TOWER", "POISON", "IRON", "MATCH", "LIFE", "LAP", "LOCK", "AMAZON", "DOCTOR", "BALL", "SEAL", "CROSS", "WHIP", "OCTOPUS"]
seed_array6 = ["KIWI", "CODE", "FILE", "BAR", "GROUND", "NOTE", "CZECH", "BACK", "WITCH", "STAFF", "MARBLE", "KETCHUP", "STAR ", "POOL", "LEAD", "WATCH", "BUGLE", "PART", "BUTTON"]
seed_array7 = ["FILM", "HIMALAYAS", "PITCH", "CROWN", "KING", "BEAR", "DISEASE", "STRAW", "SCALE", "FALSE", "SWITCH", "PORT", "GAS", "WELL", "HOLLYWOOD", "SCREEN", "FAIR ", "DRESS", "AMBULANCE"]
seed_array8 = ["AUSTRALIA", "LIMOUSINE", "VACUUM", "ATLANTIS", "FACE", "BERLIN", "PIRATE", "HORSE", "BEACH", "CHARGE", "POUND", "SUB", "ROUND", "INDIA", "FIELD", "TRAIN", "CYCLE", "TELESCOPE", "ROME"]
seed_array9 = ["PLANE", "HOTEL", "PARACHUTE", "MOUNT", "BOX", "STICK", "CHAIR", "WATER", "PYRAMID", "OPERA", "ROBOT", "EMBASSY", "HAM", "DRAFT", "BATTERY", "ENGLAND", "SMUGGLER", "FOOT", "NEW-YORK"]
seed_array10 = ["STADIUM", "DRAGON", "PASS", "GREEN", "BIKE", "SCIENTIST", "ANTARCTICA", "REVOLUTION", "POINT", "TEACHER", "THUMB", "PUMPKIN", "COOK", "COTTON", "FISH", "TUBE", "POINT", "DATE", "DRILL"]
seed_array11 = ["FROM", "BLOCK", "NET", "MOON", "OIL", "SUPERHERO", "APPLE", "POLE", "BOND", "PAN", "QUEEN", "RABBIT", "ICE-CREAM", "WASHINGTON", "PIN", "LEPRECHAUN", "NURSE", "SPACE", "HOOK"]
seed_array12 = ["LINK", "DANCE", "BEIJING", "RACKET", "FLUTE", "CARROT", "BUFFALO", "DECK", "GOLD", "TICK", "ROW", "PISTOL", "BAND", "FIRE", "HOSPITAL", "SATURN", "DUCK", "RING", "CELL"]
seed_array13 = ["COVER", "LEMON", "TAG", "BELL", "ICE", "WORM", "ALPS", "DEATH", "STOCK", "ARM", "BERMUDA", "NUT", "SOCK", "PIT", "FLY", "SHOE", "MOLE", "SNOW", "TRUNK"]
seed_array14 = ["STATE", "TORCH", "BAT", "MASS", "COMPOUND", "SLUG", "TOOTH", "PLAY", "BRUSH", "LOCK", "KNIGHT", "PIE", "SNOWMAN", "MOUSE", "HELICOPTER", "CONTRACT", "MARCH", "PLATE", "LINE"]
seed_array15 = ["TRACK", "FORCE", "NINJA", "OLYMPUS", "ROCK", "LONDON", "CASINO", "TELL", "CRASH", "SPY", "UNICORN", "CAPITAL", "PLOT", "PUPIL", "SPIDER", "ANGEL", "SPELL", "GRASS", "MUG"]
seed_array16 = ["WHOLE", "BEAT", "MAIL", "UNDERTAKER", "CONCERT", "ORGAN", "JAM", "DOG", "CONDUCTOR", "SCUBA-DIVER", "CHURCH", "KNIFE", "JACK", "COPPER", "STRING", "NIGHT", "AZTEC", "MAPLE", "ORANGE"]
seed_array17 = ["TEMPLE ", "THIEF", "NAIL", "BARK", "GIANT", "TAP", "MOUTH", "THEATER", "EGYPT", "CLUB", "SINK", "SERVER", "SCHOOL", "STRIKE", "KANGAROO", "BOARD", "CLOAK", "MICROSCOPE", "JET"]
seed_array18 = ["AGENT", "BUCK", "CRICKET", "COLD", "PENGUIN", "ROOT", "BOW", "DEGREE", "VAN", "VET", "TRIANGLE", "CAP", "CHINA", "BOLT", "POLICE", "LION", "FIGURE", "PARK", "SATELLITE"]
seed_array19 = ["LAWYER", "BILL", "DINOSAUR", "KEY", "SKYSCRAPER", "ALIEN", "CHOCOLATE", "SUIT", "SHADOW", "CENTAUR", "TURKEY", "MINE"]

seed_array.each do |seed|
  word = Word.new
  word.word = seed
  word.save
end
